class Header:
    Message_ID = ""
    Date = ""
    From = ""
    To = ""
    Subject = ""
    Mime = ""
    Content_Type = ""
    Content_Transfer_Encoding = ""
    X_From = ""
    X_To = ""
    X_cc = ""
    X_bcc = ""
    X_Folder = ""
    X_Origin = ""
    X_FileName = ""